services:
  bff:
    build: ./ms-digitalfix-bff
    container_name: bff-app
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - WORKORDERS_BASE_URL=http://workorders:8081
    depends_on:
      - workorders

  frontend:
    build:
      context: .
      dockerfile: frontend-digitalfix/dockerfile
    container_name: front-app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - bff

  workorders:
    build: ./ms-digitalfix-workorders
    container_name: workorders-app
    restart: always
    env_file:
      - .env
    expose:
      - "8081"
    environment:
      # Apuntamos al nombre del contenedor de la base de datos
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/digitalfixdb
      - SPRING_DATASOURCE_USERNAME=tu_usuario
      - SPRING_DATASOURCE_PASSWORD=tu_password
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15-alpine
    container_name: digitalfix-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=digitalfixdb
      - POSTGRES_USER=tu_usuario
      - POSTGRES_PASSWORD=tu_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tu_usuario -d digitalfixdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: